spring:
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/view/
  #      prefix: /WEB-INF/view/, /templates/

  datasource:
    #    url: jdbc:mysql://localhost:3333/bookshopweb
    url: jdbc:mysql://localhost:3306/bookshopweb
    username: root
    password: Thientho2205
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: sktththien@gmail.com
    password: gvjr jukj ovrh uvrz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    web-application-type: servlet




application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000


